name: Docker Build & Push

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      # 1️⃣ Increment version
      - name: Get next version
        id: version
        uses: reecetech/version-increment@2024.10.1
        with:
          scheme: semver
          increment: patch

      # 2️⃣ Determine Docker tags
      - name: Determine image tags
        id: tags
        run: |
          # Get the incremented version
          VERSION="v${{ steps.version.outputs.version }}"

          echo "TAG=$VERSION" >> $GITHUB_ENV

          TAGS="ghcr.io/${GITHUB_REPOSITORY}:${VERSION}"

          # Add latest only on push to main
          if [ "${{ github.event_name }}" = "push" ]; then
            TAGS="$TAGS,ghcr.io/${GITHUB_REPOSITORY}:latest"
          fi

          # If this is a PR, prepend pr-<number>
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            TAGS="ghcr.io/${GITHUB_REPOSITORY}:pr-${{ github.event.pull_request.number }}-${VERSION}"
          fi

          echo "TAGS=$TAGS" >> $GITHUB_ENV

      # 3️⃣ Login to GitHub Container Registry
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4️⃣ Build and push Docker image with caching
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.TAGS }}
          build-args: |
            APP_VERSION=${{ env.TAG }}
            PR_NUMBER=${{ github.event.pull_request.number || '' }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:${{ env.TAG }}
          cache-to: type=inline
   
      # 4️⃣ Create new tag
      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        if: github.ref == 'refs/heads/main'
        with:
          tag: ${{ steps.version.outputs.version }}
          release_name: "Release ${{ steps.version.outputs.version }}"
          draft: false

